# This file is the entry point to configure your own HTTP routes.
# Files in the routes/ subdirectory configure the routes for your dependencies.

#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }


# config/routes.yaml

# the "app_lucky_number" route name is not important yet
# config/routes.yaml

# the "app_lucky_number" route name is not important yet
app_lucky_number:
    path: /
    controller: App\Controller\LuckyController::number
    
Admin:
    path: /admin
    controller: App\Controller\AdminController::admin   
    
    
createxp:
    path: /exp/create
    controller: App\Controller\LuckyController::bd
    
create_loisir:
    path: /bd/create
    controller: App\Controller\LoisirController::create
    
edit_loisir:
    path: /bd/edit/{id}
    controller: App\Controller\LoisirController::edit

remove_loisir:
    path: /bd/remove/{id}
    controller: App\Controller\LoisirController::remove
    
valid_loisir:
    path: /bd/valid
    controller: App\Controller\LoisirController::valid
    

create_message:
    path: /contact
    controller: App\Controller\ContactController::create
    
valid_message:
    path: /contact/valid
    controller: App\Controller\ContactController::valid